name: 🐱 first pipeline

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16

    steps:
      - name: test step
        run: echo "Hello from workflow"

      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: Fenikks/word-cloud-generator

      - name: build wcg
        run: |
          make
          ls -la

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: wcg_linux
          path: artifacts/linux/*
          
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: wcg_linux

    - name: test
      run: ls -la
