name: 🐱 first pipeline

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16

    steps:
      - name: test step
        run: echo "Hello from workflow"

      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: Fenikks/word-cloud-generator

      - name: build wcg
        run: |
          make
          ls -la
      
    
